// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTTJ_cCxOeov1TUKetubOGnidvf85M7SA',
    appId: '1:1068941385988:web:477d6fa543e36835a57051',
    messagingSenderId: '1068941385988',
    projectId: 'test-82212',
    authDomain: 'test-82212.firebaseapp.com',
    storageBucket: 'test-82212.appspot.com',
    measurementId: 'G-MX397M3Z89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDn9-QDQT51NoFIvbRLl3nCvGSkl0nLmE',
    appId: '1:1068941385988:android:67f8981cd12881d2a57051',
    messagingSenderId: '1068941385988',
    projectId: 'test-82212',
    storageBucket: 'test-82212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT69sDshVg3L5rJLm8zotgpNYhz_RJuMM',
    appId: '1:1068941385988:ios:497450d0c050f66fa57051',
    messagingSenderId: '1068941385988',
    projectId: 'test-82212',
    storageBucket: 'test-82212.appspot.com',
    iosBundleId: 'com.example.flickGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT69sDshVg3L5rJLm8zotgpNYhz_RJuMM',
    appId: '1:1068941385988:ios:01201df64c837f4aa57051',
    messagingSenderId: '1068941385988',
    projectId: 'test-82212',
    storageBucket: 'test-82212.appspot.com',
    iosBundleId: 'com.example.flickGo.RunnerTests',
  );
}
